### ISSUE TITLE
Button clipping on resided window

### ISSUE THREAD

**Issue by bennyty** [TheoBr/Chrometana#14]
Hello Chrometana! 

I habitually have my chrome window resized at about 85% screen size and noticed a Bootstrap issue in on your button. 

Obviously this is on Chrometana 2.0.0 in the "Additional Settings"
At 1200px by 706px.
![](http://puu.sh/kVTDs/29b4257b01.png)
becomes
![](http://puu.sh/kVTGI/dec759fd3b.png)
At 1199px by 706px.

**Comment by kyleladd** [comment]
Thanks, to resolve this we will probably just remove the bootstrap classes from the button and just have it float:right.

Thanks again,

-Kyle
