### ISSUE TITLE
Chrometana should not redirect Bing searches from the Settings app

### ISSUE THREAD

**Issue by TheFragen** [TheoBr/Chrometana#16]
Hi there,

An example of what the subject mentions, would be going to Settings -> Update & Security -> Windows Update tab -> Click the link "Learn More" under "Looking for more info on latest updates".

This takes you to a Bing search, where you get a card with info from Microsoft about this. However, with Chrometana, it takes you to a Google search where no such information is presented. This shouldn't happen.

**Comment by kyleladd** [comment]
Thanks for bringing this to our attention.

Here are the two instances I found within the settings app and their corresponding links. I think the form querystring signifies where the request originated.
Settings -> Account -> sync your settings -> how does syncing work
http://www.bing.com/search?q=how+do+I+sync+my+settings+in+Windows+10?&filters=guid:%22e28cdb2f-7cd0-437a-b2b1-32565e3b10e7%22%20lang:%22en-us%22&form=S00028

Settings -> Update & Security -> Windows Update -> learn more
http://www.bing.com/search?q=check+for+updates+in+windows+10&filters=guid:%228a1ff15d-e8ca-4541-9e73-cfdfd5fed822%22%20lang:%22en-us%22&form=S00028

(I think) For a Bing search originating: 
- from the settings app: &form=S00028
  - (above)
- from the Bing homepage: &form=QBLH
  - https://www.bing.com/search?q=why+google+is+better+than+bing&go=Submit&qs=n&form=QBLH
- from the Bing search result page: form=QBRE
  - https://www.bing.com/search?q=why%20google%20is%20better%20than%20bing&qs=n&form=QBRE
- from Cortana: &form=WNSGPH  -OR-  &form=WNSBOX
  - https://www.bing.com/search?q=cortana+web+search&form=WNSGPH

I haven't found any documentation yet, but are others getting similar results?

Thanks,

Kyle

**Comment by TheoBr** [comment]
Kyle's pull request fixes this, expect it in a beta update soon!
