### ISSUE TITLE
Redirected searches have an extra period appended to them

### ISSUE THREAD

**Issue by yiweig** [TheoBr/Chrometana#20]
When I launch a Cortana voice search the redirected query has an extra period at the end. It doesn't affect usage, but it would be a nice quality of life fix :smile:

**Comment by TheoBr** [comment]
I'm very much struggling to reproduce this. Still an issue?

**Comment by yiweig** [comment]
@TheoBr definitely not, iirc I ended up disabling Cortana on my laptop (due to unrelated reasons). I'll close this out. Thanks for the diligent follow up tho! Not a lot of devs will flup on an almost-two year old issue.
