### ISSUE TITLE
Chrometana Not Working

### ISSUE THREAD

**Issue by whittaylor** [TheoBr/Chrometana#24]
Chrometana is no longer working (installed as Chrome extension). I became aware of this on 05/26/16, but of course, the issue could have arisen before this date without my knowing.  Also, when changing the default browser to Firefox, the auto redirect of a Cortana search no longer works.

**Comment by theowb4** [comment]
Thank you, we are very much aware of this issue. 

Microsoft has removed the ability for a user to choose what browser is opened by Cortana, more here:

http://chrometana.theo.li/2016/04/cortana-browser-choice-revoked-windows/

**Comment by TheoBr** [comment]
Sadly, Microsoft has chosen to revoke the user's ability to choose what browser is opened by a Cortana search. I wrote a detailed post about the issue here:

http://chrometana.theo.li/2016/04/cortana-browser-choice-revoked-windows/

**Comment by whittaylor** [comment]
Thanks so much for the clarification.  I suspected MS perfidy was the cause.
Whit

Whit
Taylor54819 Southern
Hls.           

La Quinta, California   92253-5633

Phone   760.219.9426        

Date: Thu, 26 May 2016 17:34:29 -0700

**Comment by whittaylor** [comment]
This is really another MS scandal.  Obviously, it's not about the "purity" or "seamless integration" of the search experience, it's about generating revenue by forcing users to use Bing.


Sir, I do salute you for giving us Chrometana.  It was a glorious few months of a most noble experiment.  May you live long and prosper.


Whit Taylor

760.219.9426






On Thu, May 26, 2016 at 5:33 PM -0700, "theowb4" <notifications@github.com> wrote:





Thank you, we are very much aware of this issue.

Microsoft has removed the ability for a user to choose what browser is opened by Cortana, more here:

http://chrometana.theo.li/2016/04/cortana-browser-choice-revoked-windows/

---
