### ISSUE TITLE
Potential Fix For Cortana Browser Redirection

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/Chrometana#25]
A current user emailed this link to me

https://gitlab.com/valinet/cortana-search-using-default-browser

Looking into it now, perhaps this is our ticket to freedom?

**Comment by skylize** [comment]
I found an article that promotes your extension even though it won't work standalone. [Force Cortana to Use Chrome](http://www.makeuseof.com/tag/force-cortana-use-chrome-google-windows-10/)

The writer offers two solutions to redirect browser opening: EdgeDeflector and  SearchWithMyBrowser and suggests Chrometana for url redirection.

I ran [EdgeDeflector](https://github.com/da2x/EdgeDeflector/releases), pointed Cortana to Chrome, then installed Chrometana. It works perfectly.

I see no reason to abandon Chrometana, as it is still a vital piece of the solution.

**Comment by TheoBr** [comment]
Due to the very hack-y nature of all current solutions (involving scripted registry hacks and enabling of deprecated functionality in Windows 10), I'm uncomfortable publicly endorsing most of these things as Chrometana-certified "solutions" to Microsoft's changes.

I am more than willing to maintain Chrometana to make sure it works with these hacks, but I'm now a full time software engineer at Twitch and my priorities are elsewhere

Thank you for bringing these solutions to my attention, I trust you understand the inherent stability and security risks in using them, and as such that you understand why we are not prioritizing development around them

**Comment by skylize** [comment]
I looked the code for EdgeDeflector. It uses the same technique as Chrometana, but at a different level of the stack. It is a Windows COM service intercepting `microsoft-edge:` urls and converting them to regular `http` or `https` urls so they inherently end up opening your default browser.
