### ISSUE TITLE
Chrometana extension infected

### ISSUE THREAD

**Issue by sflesch** [TheoBr/Chrometana#26]
Your extension on the Chrome store is infected! Please fix ASAP!

**Comment by rossinimartins** [comment]
Duplicated #27

**Comment by TheoBr** [comment]
Hey guys! Fun fact. When your extension gets taken down due to a bullshit DMCA notice, it's possible for others to somehow push updates.

I am in contact with Google and will be putting up an official press release tonight. This is absolutely maddening and I'm so sorry guys.

**Comment by TheoBr** [comment]
Update's been shipped, check #27 for more info
