### ISSUE TITLE
Comply with "Updates to Chrome Web Store Policy"

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/Chrometana#31]
New Chrome Web Store update was emailed to me a few weeks back and I didn't pay attention to it at the time. Re-read it a few days ago and realized it pretty directly affects Chrometana. I might have time to go at this this weekend, but I might not, and it needs to be done by August 1st (or we will be removed from the Chrome store...again)

The "fix" is a "prominent notice informing the user of [all] redirection[s]", so a nice javascript injection on every web page with a little "redirected by Chrometana" spit. Shouldn't be too bad.

Email attached (with personal info redacted) for clarification.

[Gmail - Updates to Chrome Web Store Policy.pdf](https://github.com/TheoBr/Chrometana/files/1179390/Gmail.-.Updates.to.Chrome.Web.Store.Policy.pdf)

**Comment by kyleladd** [comment]
Sounds like we're going to have to require permission to run the content script on all webpages. Just to check against the background page to see if they were redirected and from where (Can probably just save it to the background page's localstorage window).  Also will probably need to have an override to be able to back to the original page before redirection if the user so chooses. (onclick of 'Redirected by Chrometana from' link set background page disable redirects, go to link, stay on page and re-enable redirecting)

**Comment by TheoBr** [comment]
@kyleladd Sounds right to me. Gonna have some fun with URL flags to make this work :^)
