### ISSUE TITLE
"open example.com" command not working

### ISSUE THREAD

**Issue by Sashraan** [TheoBr/Chrometana#34]
Hey there Theo!

Just today I installed Chrometana on a fresh install of Windows, and when saying "Hey Cortana, open youtube dot com", she simply sends a search to google (nice, it's working in tandem with EdgeReflector so all is good up 'till now) and then types in "open youtube.com" in the search...

Was the open command broken?

When I access the additionnal features and tick the "Enable "Open Website"" box, it doesn't seem to save! I can refresh the page, and it returns to it's default settings...

Any help? :/

**Comment by blargle-ragequit** [comment]
I am having this issue now on Windows 10 Home version 1703 build 15063.726 with Chrome 62.0.3202.94, Edge Deflector 1.1.3.0, and Chrometana 2.0.1

**Comment by FoxInFlame** [comment]
@blargle-ragequit I also had this issue, however upon cloning Chrometana into a local copy and loading it into Chrome manually, the issue was gone. I didn't change any bit of the code.
