### ISSUE TITLE
Radio toggles in "Additional Settings" can have multiple checked at once

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/Chrometana#39]
![image](https://user-images.githubusercontent.com/6751787/33429745-eac610fc-d582-11e7-9209-a13379a3ffe3.png)

Status is generally broken. This shouldn't be too bad a fix but I've been really busy lately and I suck at javascript

**Comment by TheoBr** [comment]
Gonna throw this up on [up-for-grabs.net](http://up-for-grabs.net) tomorrow if I get a chance

https://github.com/up-for-grabs/up-for-grabs.net#add-a-project

**Comment by NigeyNige** [comment]
Hi there - I think I can fix this, the inputs just need to be put in the same radio group and the JS tested to make sure it still accepts the option. Is it okay if I have a go?

**Comment by TheoBr** [comment]
Ty for the contribution!
