### ISSUE TITLE
Chrometana isn't really broken...

### ISSUE THREAD

**Issue by cowsay652** [TheoBr/Chrometana#40]
In your Readme, you've stated that Chrometana is broken. I've found an application called [EdgeDeflector](https://github.com/da2x/EdgeDeflector) that will redirect traffic that's supposed to go to Edge to your default browser.
I thought that it would be good if I made you aware of this :)

**Comment by TheoBr** [comment]
I didn't want to recommend a regedit. Thankfully, the new version of Edge supports Chrome extensions, so we're good to go!

**Comment by iamjonny** [comment]
> I didn't want to recommend a regedit. Thankfully, the new version of Edge supports Chrome extensions, so we're good to go!

I came here to get ~2~ 3 things confirmed, this is one 👍🏻

1. Most recent reviews on extension link mention _it doesn't work on Windows 11_ - is this correct?
2. I'm using my "start menu search to search the web" (not installed extension yet as just discovered) but I think **cortana is disabled or removed** - will this affect chrometana much, apart from no voice search? eg can I use chrometana in edge to cause windows start menu [web] search to "use" a different a search provider ?
3. Do I need chrome?! **No!**

Fascinating extension- about to get a 5⭐ review if it does what I think and hope it may!
