### ISSUE TITLE
Port to Microsoft Edge?

### ISSUE THREAD

**Issue by 19lmyers** [TheoBr/Chrometana#43]
Currently, there is no equivalent extension for Microsoft Edge. 
But Chrome extensions _can_ be ported to run on Microsoft Edge.

Is there any change of a Microsoft Edge version being supported?

**Comment by TheoBr** [comment]
With the new version of Edge, you should be able to install Chrometana from the Chrome web store. I have submitted Chrometana to the Edge store as well
