### ISSUE TITLE
Update stale deps

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/Chrometana#61]
Most of the dependencies are ancient. We should update them and thoroughly test to make sure the updates don't break anything

**Comment by YoussefMahmod** [comment]
Hello @TheoBr,
Can i work on it ?

**Comment by TheoBr** [comment]
@YoussefMahmod Thank you for asking! I'll assign this one to you. Make sure you test the build before and after to note any regressions :)

**Comment by t3dotgg** [comment]
Closed by https://github.com/TheoBr/Chrometana/pull/62
