### ISSUE TITLE
Does not redirect from cn.bing.com and other bing addresses

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/Chrometana#7]
Going through tickets now, this is a big thing we're missing lol. The ticket:

"The default search site for chinese win 10 system is cn.bing.com, it does not redirect to google. I guess it only redirects www.bing.com. Can fix this? Thx."

**Comment by kyleladd** [comment]
I think this is essentially requires us to translate Bing subdomains into Google top-level domains. Correct?
https://en.wikipedia.org/wiki/List_of_Google_domains
http://onlinehelp.microsoft.com/en-us/bing/ff808526.aspx
Ex: www.cn.bing.com to www.google.cn
If a match is not found, default to www?

**Comment by ClairePitman** [comment]
I mean we could do that but it would be a pain. Or we can just use the custom url feature that is in the woks along with a regex tweak.

**Comment by kyleladd** [comment]
yahoo looks like: https://everything.yahoo.com/world/
duckduckgo seems to just have a user setting and we shouldn't have to worry about it: https://duckduckgo.com/settings

**Comment by TheoBr** [comment]
Another thing I've been considering - should we have Chrometana default to Chrome's search engine, and then separate custom entirely? It would get us out of all of these problems and arguably offer a better user experience

**Comment by ClairePitman** [comment]
I like that idea but is it even possible?

**Comment by TheoBr** [comment]
Very easily, I'm sure there's either a way to grab the user's current search engine, or an API to perform a search through Chrome's default method

**Comment by ClairePitman** [comment]
That honestly seems to be the logical option. It leaves the settings page in a bit of a weird spot but....

**Comment by TheoBr** [comment]
We fixed this awhile ago. If I'm incorrect, feel free to re-open
